chore: Update README to reflect the need for an old enough setuptools
`setuptools.command.test` was removed in setuptools 72.x, so we can't
use 72.x or newer without updating our ion-python's build/test setup.
In addition, there was a breaking change, it seems, in 71.x, to
`canonicalize_version()`.

By selecting setuptools **prior** to 71.0.0, the build and tests run
successfully.

Errors encountered:

With setuptools 72.x:
```
...
    import setuptools.command.test as orig
ModuleNotFoundError: No module named 'setuptools.command.test'
```

With setuptools 71.x:
```
...
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```